development:
  adapter: postgresql
  database: haxor_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: isthissafe?
  host: localhost

test:
  adapter: postgresql
  database: haxor_test
  pool: 5
  timeout: 5000
  username: postgres
  password: isthissafe?
  host: localhost

production:
  adapter: postgresql
  database: haxor_prod
  pool: 5
  timeout: 5000
  username: postgres
  password: isthissafe?
  host: localhost
